
name: jobs pipeline
on:
    push:
        branches:
            - main

jobs:
    job1-data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: run job1.py
              run: python job1.py
    
    job2-data:
        runs-on: ubuntu-latest
        needs: job1-data
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: run job2.py
              run: python job2.py

    job3-data:
        runs-on: ubuntu-latest
        needs: job1-data
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: run job3.py
              run: python job3.py
    
    job4-data:
        runs-on: ubuntu-latest
        needs: job2-data
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: run job4.py
              run: python job4.py
                 
    job5-data:
        runs-on: ubuntu-latest
        needs: job3-data
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: run job5.py
              run: python job5.py
                 
    job6-data:
        runs-on: ubuntu-latest
        needs: [job4-data,job5-data]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: run job6.py
              run: python job6.py